volumes:
  dev-db-volume: {}
services:
  dev-pg1:
    container_name: dbpg1
    hostname: lala
    image: bitnami/postgresql:17.2.0
    environment:
      POSTGRESQL_DATABASE: lab1
      POSTGRESQL_USERNAME: eoeqs
      POSTGRESQL_PASSWORD: eoeqs
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eoeqs"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend1:

    container_name: back_app1
    hostname: bbb
    depends_on:
      dev-pg1:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8080:8080'

  frontend1:
    container_name: front_app1
    depends_on:
      - backend1
    build:
      context: auth-app
      dockerfile: Dockerfile

    ports:
      - '8686:443'
    volumes:
      - ./auth-app/alegzandra_lab_tls.crt:/etc/nginx/alegzandra_lab_tls.crt
      - ./auth-app/alegzandra_lab_tls.key:/etc/nginx/alegzandra_lab_tls.key
      - ./auth-app/nginx.conf:/etc/nginx/nginx.conf